server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 20M;

    # API isteklerini try_files tuzağından kurtarıyoruz
    location /api/ {
        # Eğer bir backend konteynırın varsa buraya proxy_pass gelir.
        # Eğer yoksa, Nginx'in buraya HTML dönmesini engelleyelim:
        default_type application/json;
        return 404 '{"error": "API yolu bulunamadi, backend ayarini kontrol et."}';
    }

    location / {
        include /etc/nginx/mime.types;
        try_files $uri $uri/ /index.html;
    }
}
