server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;

    # 400 hatasını önlemek için buffer ayarları
    client_max_body_size 16M;
    large_client_header_buffers 4 16k;

    location / {
        # 405 hatasını (POST to static) önlemek için özel kural
        error_page 405 =200 $uri;
        
        try_files $uri $uri/ /index.html;
    }

    # Statik dosyalar için cache ayarı (Hız için)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
