server {
    listen 80;
    server_name localhost;

    # Kök dizini burada tanımlayalım
    root /usr/share/nginx/html;
    index index.html;

    # Dosya türlerini (MIME types) tanıması için zorunlu
    include /etc/nginx/mime.types;

    location / {
        # Dosyayı ara, bulamazsan index.html'e yönlendir
        try_files $uri $uri/ /index.html;
    }

    # Statik dosyaların (JS, CSS, Resim) hızlı yüklenmesi için ayar
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
