name: Deploy Guidelonia
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # ENV_FILE sırrını da içeri aktarıyoruz
          envs: ENV_FILE_CONTENT
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE }}
         script: |
          mkdir -p /home/web_apps/guidelonia
          cd /home/web_apps/guidelonia
          
          # 1. Kodları Çek
          if [ ! -d ".git" ]; then
            git clone https://github.com/agonian/EverGuide.git .
          else
            git pull origin main
          fi

          # 2. .env Dosyasını "Işınla" (GitHub Secret'tan oluştur)
          echo "$ENV_FILE_CONTENT" > .env
          
          # 3. Build Al ve Başlat (Artık .env var, build başarılı olacak)
          docker compose up -d --build
